ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST:  mongodb-dev.girisha.online
REDIS_HOST: redis-dev.girisha.online
CATALOGUE_HOST : catalogue-dev.girisha.online
RABBITMQ_HOST: rabbitmq-dev.girisha.online
MYSQL_HOST: mysql-dev.girisha.online
USER_HOST : user-dev.girisha.online
CART_HOST: cart-dev.girisha.online
PAYMENT_HOST: payment-dev.girisha.online
SHIPPING_HOST: shipping-dev.girisha.online