- name : app setup
  ansible.builtin.import_role:
    name : common
    tasks_from: app-setup.yaml

- name : java setup
  ansible.builtin.import_role:
    name : common
    tasks_from: java.yaml

- name : moving shipping jar file  
  ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
  args:
    chdir : /app

- name : install dependencies
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: pip3.9
  loop:
  - cryptography
  - PyMYSQL

- name : systemd restart
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup.yaml

- name: import shipping data into mysql
  community.mysql.mysql_db:
    state: import
    name: all
    login_host: "{{ MYSQL_HOST }}"
    login_user: root
    login_password: "{{ MYSQL_ROOT_PASSWORD }}"
    target: "{{ item }}"
  loop:
  - /app/db/schema.sql
  - /app/db/app-user.sql 
  - /app/db/master-data.sql

- name : shipping restart
  ansible.builtin.service:
    name: shipping
    state: restarted
    enabled: yes



