- name : installing python and dependencies module
  ansible.builtin.package:
    name : "{{ item }}"
    state: present
  loop:
  - python3
  - python3-devel
  - gcc

- name : installing dependencies
  ansible.builtin.pip:
    requirements: requirements.txt
    executable: pip3.9
  args:
    chdir: /app